### PR TITLE
Update README.md

### LINKED ISSUE #33: Update README.md

### PR DESCRIPTION
**Pull request by XinghuaJulia**
Fixes #33

### CODE REVIEW

**Comment by ulricolo7** [comment]
LGTM!

**Review by psh12320 — COMMENTED** [review]
Overall LGTM, but should change Ui.png to be width 726px times height 593px

**Review by marraknas — APPROVED** [review]
LGTM

**Review by marraknas — COMMENTED** [review]
LGTM!

**Pull request merged**
